project:
  type: website
  output-dir: docs

website:
  title: "BIOEST 2024-25"
  navbar:
    left:
      - href: index.qmd
        text: Programa
      - href: Practica0.qmd
        text: Pr치ctica 0
      - href: Practica1.qmd
        text: Pr치ctica 1
      - href: Practica2.qmd
        text: Pr치ctica 2
      - href: Practica3.qmd
        text: Pr치ctica 3

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    link-external-newwindow: true

editor: visual

